//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewProfiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserLogins = new HashSet<UserLogin>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public System.Guid ProfileId { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual ICollection<UserLogin> UserLogins { get; set; }
    }
}
